name: ci

on:
  push:
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'
  schedule:
    - cron: "0 0 * * *" # every day at midnight

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  ros_ci:
    name: ${{ matrix.ros_distro }} CI
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-${{ matrix.ubuntu_codename }}-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ros_distro: jazzy
            ubuntu_codename: noble
          - ros_distro: lyrical
            ubuntu_codename: resolute
          - ros_distro: rolling
            ubuntu_codename: resolute
    steps:
      - uses: actions/checkout@v6
      - uses: ros-tooling/action-ros-ci@v0.4
        id: action_ros_ci_step
        with:
          target-ros2-distro: ${{ matrix.ros_distro }}
          package-name: |
            linux_i2c_demos
            linux_i2c_devices
            linux_i2c_interface
