name: ci

on:
  push:
  pull_request:

jobs:
  build_and_test:
    name: humble
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: humble, ROS_REPO: testing}
          - {ROS_DISTRO: humble, ROS_REPO: main}
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}